import mongoose from "mongoose";

const federalSchema = new mongoose.Schema({
    // SECTION 1: BASIC INFORMATION
    applicantNameAndBranchDetails: {
        required:true,
        type:String
    },
    ownerOfTheProperty: {
        required:true,
        type:String
    },
    nameOfTheProspectivePurchaser: String,
    builderNameAndRERAID: String,
    propertyDescription: String,
    personMetOnSite: String,
    propertyAddressAsPerSiteVisit: String,
    businessName: String,
    houseDoorUnitFlatShopOfficeGalaNo: String,
    plotNo: String,
    floor: String,
    projectNameBuildingName: String,
    localitySubLocality: String,
    streetNameRoadNo: String,
    nearestLandmark: String,
    cityTown: String,
    village: String,
    pincode: String,
    plotNoSurveyNoKhasraNo: String,
    subZone: String,
    villageTechnical: String,
    subDistrictTaluka: String,
    district: String,
    state: String,
    legalAddressOfProperty: String,

    // SECTION 2: PROPERTY DETAILS (Existing)
    propertyType: String,
    propertyUsage: String,
    permittedUsageOfTheProperty: String,
    withinMunicipalLimits: String,
    municipalNumber: String,
    constructionStatus: String,
    percentComplete: String,
    percentRecommended: String,
    typeOfOccupancy: String,
    tenureIfSelfOccupied: String,
    tenureIfVacant: String,
    ifRentedTenantDetails: String,
    customerRelationshipWithOccupant: String,
    ownershipType: String,
    totalNoOfBlocksBuildings: String,
    noOfFloors: String,
    noOfUnitsTotalUnits: String,
    noOfUnitsUnitsOnEachFloor: String,
    yearBuiltAgeOfProperty: String,
    yearBuiltAgeOfPropertyYears: String,
    residualAgeOfTheProperty: String,
    maintenanceLevelOfBuilding: String,
    amenities: String,
    amenitiesLifts: String,
    buildingConstructedAccordingToPlan: String,

    // SECTION 3: UNIT DETAILS
    basement: String,
    groundFloor: String,
    firstFloor: String,
    secondFloor: String,
    thirdFloor: String,
    fourthFloor: String,
    fifthFloor: String,

    // SECTION 4: SURROUNDING LOCALITY DETAILS
    typeOfArea: String,
    classificationOfArea: String,
    developmentInVicinityPercent: String,
    qualityOfInfrastructureInVicinity: String,
    classOfLocality: String,
    natureOfLocality: String,
    detailsOfTheRoute: String,
    hasDirectIndependentAccess: String,
    propertyAccessibleByCar: String,
    proximityToCivicAmenities: String,
    nearestRailwayStation: String,
    nearestHospital: String,
    nearestCityCenter: String,
    isCornerProperty: String,
    propertyIdentifiedThrough: String,
    propertyDemarcated: String,
    natureOfLandTypeOfUse: String,
    ifOthersGiveDetails: String,
    generalDescriptionOfLayout: String,
    ifOthersGiveDetails2: String,
    otherDevelopmentsOnProperty: String,
    approachRoadDetails: String,
    approachRoadDetailsWidth: String,
    marketability: String,
    encroachmentDetails: String,
    isPropertyProneToDisaster: String,
    anyLocationalAdvantages: String,

    // SECTION 5: PHYSICAL DETAILS
    boundariesNorthSiteVisit: String,
    boundariesNorthLegalDocuments: String,
    boundariesSouthSiteVisit: String,
    boundariesSouthLegalDocuments: String,
    boundariesEastSiteVisit: String,
    boundariesEastLegalDocuments: String,
    boundariesWestSiteVisit: String,
    boundariesWestLegalDocuments: String,
    boundariesMatchingWithSite: String,

    // SECTION 6: STRUCTURAL DETAILS
    typeOfConstructionStructure: String,
    qualityOfConstruction: String,
    foundationType: String,
    roofType: String,
    masonryType: String,
    walls: String,
    doorsAndWindows: String,
    finishing: String,
    flooring: String,
    anyOtherConstructionSpecifications: String,
    doesPropertyFallInDemolitionList: String,

    // SECTION 7: PROPERTY STAGE OF CONSTRUCTION
    foundationAllottedConstructionStage: String,
    foundationPresentCompletion: String,
    foundationNoOfFloorsCompleted: String,
    plinthAllottedConstructionStage: String,
    plinthPresentCompletion: String,
    plinthNoOfFloorsCompleted: String,
    brickworkUptoSlabAllottedConstructionStage: String,
    brickworkUptoSlabPresentCompletion: String,
    brickworkUptoSlabNoOfFloorsCompleted: String,
    slabRCCCastingAllottedConstructionStage: String,
    slabRCCCastingPresentCompletion: String,
    slabRCCCastingNoOfFloorsCompleted: String,
    insideOutsidePlasterAllottedConstructionStage: String,
    insideOutsidePlasterPresentCompletion: String,
    insideOutsidePlasterNoOfFloorsCompleted: String,
    flooringWorkAllottedConstructionStage: String,
    flooringWorkPresentCompletion: String,
    flooringWorkNoOfFloorsCompleted: String,
    electrificationWorkAllottedConstructionStage: String,
    electrificationWorkPresentCompletion: String,
    electrificationWorkNoOfFloorsCompleted: String,
    woodworkPaintingAllottedConstructionStage: String,
    woodworkPaintingPresentCompletion: String,
    woodworkPaintingNoOfFloorsCompleted: String,
    totalCompletionAllottedConstructionStage: String,
    totalCompletionPresentCompletion: String,
    totalCompletionNoOfFloorsCompleted: String,
    recommendedAmountInPercent: String,

    // SECTION 8: DOCUMENTS AND PERMISSIONS
    layoutPlansDetails: String,
    buildingPlanDetails: String,
    constructionPermissionDetails: String,
    occupationCompletionCertificateDetails: String,
    titleDocumentsVerificationCertificate: String,
    latestOwnershipDocument: String,
    anyOtherDocuments: String,
    deviationsObserved: String,
    constructionDoneAsPerLocalBylaws: String,
    permissibleFSI: String,
    isPropertyMortgagedOrDisputed: String,
    valuePurchasePricePaid: String,
    presentMarketRate: String,
    detailsOfRecentTransaction: String,

    // SECTION 9: VALUATION REPORT - Land
    landAreaAsPerSite: String,
    landAreaAsPerPlan: String,
    landAreaAsPerLegalDoc: String,
    undividedShareOfLand: String,
    adoptedLandArea: String,
    adoptedLandRate: String,
    guidelineRateForLand: String,
    landValue: String,

    // SECTION 9: VALUATION REPORT - Building
    basementFloorAreaAsPerSite: String,
    basementFloorAreaAsPerDocuments: String,
    basementFloorDeviation: String,
    basementFloorAdoptedBuiltUpArea: String,
    basementFloorAdoptedConstructionRate: String,
    basementFloorReplacementCost: String,
    stiltFloorAreaAsPerSite: String,
    stiltFloorAreaAsPerDocuments: String,
    stiltFloorDeviation: String,
    stiltFloorAdoptedBuiltUpArea: String,
    stiltFloorAdoptedConstructionRate: String,
    stiltFloorReplacementCost: String,
    groundFloorAreaAsPerSite: String,
    groundFloorAreaAsPerDocuments: String,
    groundFloorDeviation: String,
    groundFloorAdoptedBuiltUpArea: String,
    groundFloorAdoptedConstructionRate: String,
    groundFloorReplacementCost: String,
    firstFloorAreaAsPerSite: String,
    firstFloorAreaAsPerDocuments: String,
    firstFloorDeviation: String,
    firstFloorAdoptedBuiltUpArea: String,
    firstFloorAdoptedConstructionRate: String,
    firstFloorReplacementCost: String,
    secondFloorAreaAsPerSite: String,
    secondFloorAreaAsPerDocuments: String,
    secondFloorDeviation: String,
    secondFloorAdoptedBuiltUpArea: String,
    secondFloorAdoptedConstructionRate: String,
    secondFloorReplacementCost: String,
    thirdFloorAreaAsPerSite: String,
    thirdFloorAreaAsPerDocuments: String,
    thirdFloorDeviation: String,
    thirdFloorAdoptedBuiltUpArea: String,
    thirdFloorAdoptedConstructionRate: String,
    thirdFloorReplacementCost: String,
    fourthFloorAreaAsPerSite: String,
    fourthFloorAreaAsPerDocuments: String,
    fourthFloorDeviation: String,
    fourthFloorAdoptedBuiltUpArea: String,
    fourthFloorAdoptedConstructionRate: String,
    fourthFloorReplacementCost: String,
    fifthFloorAreaAsPerSite: String,
    fifthFloorAreaAsPerDocuments: String,
    fifthFloorDeviation: String,
    fifthFloorAdoptedBuiltUpArea: String,
    fifthFloorAdoptedConstructionRate: String,
    fifthFloorReplacementCost: String,
    totalAreaAsPerSite: String,
    totalAreaAsPerDocuments: String,
    totalDeviation: String,
    totalAdoptedBuiltUpArea: String,
    totalAdoptedConstructionRate: String,
    totalReplacementCost: String,
    depreciationPercent: String,
    netReplacementCost: String,
    noOfCarParking: String,
    valueOfParking: String,
    valueOfOtherAmenities: String,
    buildingValueInsurableValue: String,
    buildingValueAsPerGovtGuidelineRate: String,

    // SECTION 9: FINAL VALUES
    estimatedCostToComplete: String,
    guidelineValue: String,
    estimatedRentalValue: String,
    marketValue: String,
    marketValueInWords: String,
    sourceForMarketValue: String,
    realizableValue: String,
    realizableValuePercent: String,
    forcedSaleValue: String,
    forcedSaleValuePercent: String,

    // SECTION 10: REMARKS & DECLARATION
    remarksPropertyDescription: {
        type: String,
        default: 'THE PROPERTY IS A RESIDENTIAL BUILDING WHOSE CONSTRUCTION IS UNDER PROGRESS AND PLASTERING COMPLETED. THE PENDING WORKS ARE SANITARY FITTINGS, ELECTRICAL SWITCHES FINISHING WORKS AND FLOORING'
    },
    declarationPoint1: {
        type: String,
        default: 'The information furnished in this report is true and correct to the best of my knowledge and belief.'
    },
    declarationPoint2: {
        type: String,
        default: 'I have no direct or indirect interest in the property valued.'
    },
    declarationPoint3: {
        type: String,
        default: 'I / My representative MYSELF have/ has personally visited the property by going to the site and inspected all items thoroughly.'
    },
    declarationPoint4: {
        type: String,
        default: 'The legal aspects are out of the scope of this valuation report.'
    },
    declarationPoint5: {
        type: String,
        default: 'I have never been debarred or convicted by any court of law.'
    },
    declarationPoint6: {
        type: String,
        default: 'The valuation report has been prepared for mortgage purpose.'
    },

    // SECTION 11: Annexure I
    constructionDeviationApprovedPlanAvailable: String,
    constructionDeviationDeviationOnSecurityProperty: String,
    constructionDeviationPropertyTaxPaidReceipts: String,
    constructionDeviationLatestLandRecordAvailability: String,
    constructionDeviationFSIRARFARLocalAuthority: String,
    constructionDeviationMaxDeviationPermitted: String,
    constructionDeviationFSIRARFARAgreement: String,
    constructionDeviationFSIRARFARValuerConfirmed: String,
    constructionDeviationPropertyAcceptedAsSecurity: String,
    constructionDeviationHerebyConfirmCertify: String,

    latitude: Number,
    longitude: Number,

    images: [{
        fileName: {
            type:String,
            required:true
        },
        filePath: {
            type:String,
            required:true
        }
    }]
},{
    timestamps:true
});

const federal = mongoose.model('Federal_data', federalSchema);
export default federal;